env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
  - plugin:react/jsx-runtime
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-unused-vars": "error"
  "@typescript-eslint/consistent-type-definitions": ["error", "type"]
  "react/jsx-filename-extension": [1, { "extensions": [".tsx"] }]
  react/function-component-definition: 0
  arrow-body-style: 0
  "import/prefer-default-export": 0
  no-restricted-exports: 0
  "react/jsx-props-no-spreading": 0
  "import/extensions":
    - "error"
    - "ignorePackages"
    - "js": "never"
      "jsx": "never"
      "ts": "never"
      "tsx": "never"
settings:
  "import/resolver":
    "node":
      "extensions": [".js", ".jsx", ".ts", ".tsx"]
